INSERT INTO `family` (`id`, `name`) VALUES (14200, "Angemon");
INSERT INTO `family` (`id`, `name`) VALUES (18200, "Roi angemon");
INSERT INTO `family` (`id`, `name`) VALUES (12800, "Elémentaire faible");
INSERT INTO `family` (`id`, `name`) VALUES (10800, "Elémentaire");
INSERT INTO `family` (`id`, `name`) VALUES (10900, "Garuda");
INSERT INTO `family` (`id`, `name`) VALUES (12100, "Harpu");
INSERT INTO `family` (`id`, `name`) VALUES (10600, "Cerbère");
INSERT INTO `family` (`id`, `name`) VALUES (13200, "Howl");
INSERT INTO `family` (`id`, `name`) VALUES (10200, "Diablotin");
INSERT INTO `family` (`id`, `name`) VALUES (10300, "Lutin");
INSERT INTO `family` (`id`, `name`) VALUES (10700, "L'ours de guerre");
INSERT INTO `family` (`id`, `name`) VALUES (10400, "Yéti");
INSERT INTO `family` (`id`, `name`) VALUES (11100, "Salamander");
INSERT INTO `family` (`id`, `name`) VALUES (15200, "Vagabond");
INSERT INTO `family` (`id`, `name`) VALUES (14800, "Viking");
INSERT INTO `family` (`id`, `name`) VALUES (10100, "Fée");
INSERT INTO `family` (`id`, `name`) VALUES (14900, "Amazone");
INSERT INTO `family` (`id`, `name`) VALUES (19000, "Mammouth de combat");
INSERT INTO `family` (`id`, `name`) VALUES (13700, "Bearman");
INSERT INTO `family` (`id`, `name`) VALUES (18500, "Chasseur de bêtes");
INSERT INTO `family` (`id`, `name`) VALUES (15600, "Chasseur de tête");
INSERT INTO `family` (`id`, `name`) VALUES (17200, "Maître ivre");
INSERT INTO `family` (`id`, `name`) VALUES (19300, "Cowgirl");
INSERT INTO `family` (`id`, `name`) VALUES (11400, "Golem");
INSERT INTO `family` (`id`, `name`) VALUES (11500, "Griffon");
INSERT INTO `family` (`id`, `name`) VALUES (16000, "Faucheuse");
INSERT INTO `family` (`id`, `name`) VALUES (10500, "Harpie");
INSERT INTO `family` (`id`, `name`) VALUES (12000, "Haut élémentaire");
INSERT INTO `family` (`id`, `name`) VALUES (15800, "Lutin champion");
INSERT INTO `family` (`id`, `name`) VALUES (11700, "Inferno");
INSERT INTO `family` (`id`, `name`) VALUES (11000, "Inugami");
INSERT INTO `family` (`id`, `name`) VALUES (16500, "Armure vivante");
INSERT INTO `family` (`id`, `name`) VALUES (17800, "Homme-lézard");
INSERT INTO `family` (`id`, `name`) VALUES (15400, "Archer Magique");
INSERT INTO `family` (`id`, `name`) VALUES (15000, "Chat martial");
INSERT INTO `family` (`id`, `name`) VALUES (17700, "Minotaure");
INSERT INTO `family` (`id`, `name`) VALUES (15900, "Sorcière mystique");
INSERT INTO `family` (`id`, `name`) VALUES (18700, "Chevalier pingouin");
INSERT INTO `family` (`id`, `name`) VALUES (11300, "Serpent");
INSERT INTO `family` (`id`, `name`) VALUES (18400, "Taoiste");
INSERT INTO `family` (`id`, `name`) VALUES (14000, "Loup-garou");
INSERT INTO `family` (`id`, `name`) VALUES (18800, "Roi barbare");
INSERT INTO `family` (`id`, `name`) VALUES (18000, "Brownie le Magicien");
INSERT INTO `family` (`id`, `name`) VALUES (16200, "Chevalier de la mort");
INSERT INTO `family` (`id`, `name`) VALUES (15300, "Prêtre Epikion");
INSERT INTO `family` (`id`, `name`) VALUES (13400, "Joker");
INSERT INTO `family` (`id`, `name`) VALUES (18100, "Kobold Bombeur");
INSERT INTO `family` (`id`, `name`) VALUES (17300, "Kung-fu girl");
INSERT INTO `family` (`id`, `name`) VALUES (16300, "Liche");
INSERT INTO `family` (`id`, `name`) VALUES (11200, "Kitsuné");
INSERT INTO `family` (`id`, `name`) VALUES (13500, "Ninja");
INSERT INTO `family` (`id`, `name`) VALUES (14100, "Voleur fantôme");
INSERT INTO `family` (`id`, `name`) VALUES (13900, "Pierrette");
INSERT INTO `family` (`id`, `name`) VALUES (15500, "Rakshasa");
INSERT INTO `family` (`id`, `name`) VALUES (16900, "Samouraï");
INSERT INTO `family` (`id`, `name`) VALUES (18300, "Danseur du ciel");
INSERT INTO `family` (`id`, `name`) VALUES (13300, "Succube");
INSERT INTO `family` (`id`, `name`) VALUES (11800, "Sylphe");
INSERT INTO `family` (`id`, `name`) VALUES (11900, "Sylphide");
INSERT INTO `family` (`id`, `name`) VALUES (11600, "Ondine");
INSERT INTO `family` (`id`, `name`) VALUES (14700, "Vampire");
INSERT INTO `family` (`id`, `name`) VALUES (17000, "Archange");
INSERT INTO `family` (`id`, `name`) VALUES (17400, "Moine bestial");
INSERT INTO `family` (`id`, `name`) VALUES (14600, "Chimère");
INSERT INTO `family` (`id`, `name`) VALUES (14400, "Dragon");
INSERT INTO `family` (`id`, `name`) VALUES (16600, "Chevalier dragon");
INSERT INTO `family` (`id`, `name`) VALUES (17900, "Dame de l'Enfer");
INSERT INTO `family` (`id`, `name`) VALUES (19200, "Ifrit");
INSERT INTO `family` (`id`, `name`) VALUES (16800, "Roi singe");
INSERT INTO `family` (`id`, `name`) VALUES (16100, "Fille occulte");
INSERT INTO `family` (`id`, `name`) VALUES (15700, "Oracle");
INSERT INTO `family` (`id`, `name`) VALUES (14500, "Phénix");
INSERT INTO `family` (`id`, `name`) VALUES (18600, "Pionnier");
INSERT INTO `family` (`id`, `name`) VALUES (18900, "Reine polaire");
INSERT INTO `family` (`id`, `name`) VALUES (13800, "Valkyrie");
INSERT INTO `family` (`id`, `name`) VALUES (19100, "Reine des fées");
INSERT INTO `family` (`id`, `name`) VALUES (19500, "Requin coursier");
INSERT INTO `family` (`id`, `name`) VALUES (19400, "Capitaine pirate");
INSERT INTO `family` (`id`, `name`) VALUES (19600, "Sirène");
INSERT INTO `family` (`id`, `name`) VALUES (19700, "Empereur de la mer");
INSERT INTO `family` (`id`, `name`) VALUES (19800, "Chevalier magique");
INSERT INTO `family` (`id`, `name`) VALUES (16700, "Archer magique d'élite");
INSERT INTO `family` (`id`, `name`) VALUES (19900, "Assassin");
INSERT INTO `family` (`id`, `name`) VALUES (20100, "Agent néostone");
INSERT INTO `family` (`id`, `name`) VALUES (20200, "Expert en art martial");
INSERT INTO `family` (`id`, `name`) VALUES (20000, "Combattant néostone");
INSERT INTO `family` (`id`, `name`) VALUES (20300, "Momie");
INSERT INTO `family` (`id`, `name`) VALUES (20400, "Anubis");
INSERT INTO `family` (`id`, `name`) VALUES (20600, "Horus");
INSERT INTO `family` (`id`, `name`) VALUES (20500, "Reine du désert");
INSERT INTO `family` (`id`, `name`) VALUES (20800, "Frankenstein");
INSERT INTO `family` (`id`, `name`) VALUES (20700, "Citrouille de Halloween");
INSERT INTO `family` (`id`, `name`) VALUES (20900, "Elfe patrouilleur");
INSERT INTO `family` (`id`, `name`) VALUES (21000, "Harg");
INSERT INTO `family` (`id`, `name`) VALUES (21100, "Roi des fées");
INSERT INTO `family` (`id`, `name`) VALUES (21200, "Guerrier panda");
INSERT INTO `family` (`id`, `name`) VALUES (1000100, "Homunculus(Attaque)");
INSERT INTO `family` (`id`, `name`) VALUES (21300, "Maître des dés");
INSERT INTO `family` (`id`, `name`) VALUES (21400, "Joueuse de harpe");
INSERT INTO `family` (`id`, `name`) VALUES (21500, "Licorne");
INSERT INTO `family` (`id`, `name`) VALUES (1000200, "Homunculus(Support)");
INSERT INTO `family` (`id`, `name`) VALUES (21800, "Paladin");
INSERT INTO `family` (`id`, `name`) VALUES (21900, "Danseuse aux chakrams");
INSERT INTO `family` (`id`, `name`) VALUES (22000, "Guerrière au Boomerang");
INSERT INTO `family` (`id`, `name`) VALUES (22100, "Dryade");
INSERT INTO `family` (`id`, `name`) VALUES (22200, "Druide");
INSERT INTO `family` (`id`, `name`) VALUES (22400, "Guerrier géant");
INSERT INTO `family` (`id`, `name`) VALUES (22600, "Empereur des foudres");
INSERT INTO `family` (`id`, `name`) VALUES (22700, "Sniper Mk.I");
INSERT INTO `family` (`id`, `name`) VALUES (22900, "Cannon Girl");
INSERT INTO `family` (`id`, `name`) VALUES (23000, "Seigneur Vampire");
INSERT INTO `family` (`id`, `name`) VALUES (23100, "Démon");
INSERT INTO `family` (`id`, `name`) VALUES (23300, "Gargouille");
INSERT INTO `family` (`id`, `name`) VALUES (23500, "Chasseresse au fauve");
INSERT INTO `family` (`id`, `name`) VALUES (23700, "Peintre");
INSERT INTO `family` (`id`, `name`) VALUES (23900, "Virtuose à la cithare");
INSERT INTO `family` (`id`, `name`) VALUES (24500, "Striker");
INSERT INTO `family` (`id`, `name`) VALUES (24600, "Griffes de l'ombre");
INSERT INTO `family` (`id`, `name`) VALUES (24700, "Slayer");
INSERT INTO `family` (`id`, `name`) VALUES (24800, "Maître des poisons");
INSERT INTO `family` (`id`, `name`) VALUES (24900, "Danseuse aux lames");
INSERT INTO `family` (`id`, `name`) VALUES (25000, "Onmyouji");
INSERT INTO `family` (`id`, `name`) VALUES (25100, "Onimusha");
INSERT INTO `family` (`id`, `name`) VALUES (25200, "Mage");
INSERT INTO `family` (`id`, `name`) VALUES (25300, "Surfeur céleste");
INSERT INTO `family` (`id`, `name`) VALUES (25400, "ROBO");
INSERT INTO `family` (`id`, `name`) VALUES (25600, "Totémiste");
INSERT INTO `family` (`id`, `name`) VALUES (25700, "Maître d'armes");
INSERT INTO `family` (`id`, `name`) VALUES (25800, "Forgeronne");
INSERT INTO `family` (`id`, `name`) VALUES (25900, "Ombromancien");
INSERT INTO `family` (`id`, `name`) VALUES (26000, "Hypnomiaou");
INSERT INTO `family` (`id`, `name`) VALUES (26100, "Ange de combat");
INSERT INTO `family` (`id`, `name`) VALUES (26700, "Guerrier sucette");
INSERT INTO `family` (`id`, `name`) VALUES (26800, "Princesse Pudding");
INSERT INTO `family` (`id`, `name`) VALUES (26900, "Garde Macaron");
INSERT INTO `family` (`id`, `name`) VALUES (27000, "Dame Thé noir");
INSERT INTO `family` (`id`, `name`) VALUES (27100, "Chevalier Choco");
INSERT INTO `family` (`id`, `name`) VALUES (27200, "Marionnettiste");
INSERT INTO `family` (`id`, `name`) VALUES (27800, "Double Lame");
INSERT INTO `family` (`id`, `name`) VALUES (27900, "Commandeur d'acier");
INSERT INTO `family` (`id`, `name`) VALUES (28000, "Guerrier du désert");
INSERT INTO `family` (`id`, `name`) VALUES (28100, "Gladiatrice");
INSERT INTO `family` (`id`, `name`) VALUES (28200, "Reine des mercenaires");
INSERT INTO `family` (`id`, `name`) VALUES (28300, "Indra");
INSERT INTO `family` (`id`, `name`) VALUES (28500, "Asura");
INSERT INTO `family` (`id`, `name`) VALUES (28600, "Demoiselle des Enfers");
